class-rooms:
  url: "https://class-rooms.herokuapp.com/"

jobs:
  heroku:
    enable-refresh: false
    refresh: "0 0/5 * * * *"

server:
  port: 8002

spring:
  application:
    name: classroom-api
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class_rooms_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ealvarez
    password: delta231092
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
